# Learn Posture

use machine learning to recognize robot's posture (following the example in [scikit-learn-intro.ipynb](./scikit-learn-intro.ipynb) )

## 1. Data collection

We have colleceted data before, you need to add new data if you want to add new posture.

* the dateset are in *robot_pose_data* folder
* each file contains the data belongs to this posture, e.g. the data in *Back* file are collected when robot was in "Back" posture
* the data file can be load by ```pickle```, e.g. ```pickle.load(open('Back', 'rb'))```, the data is a list of feature data
* the features (e.g. each row of the data) are ['LHipYawPitch', 'LHipRoll', 'LHipPitch', 'LKneePitch', 'RHipYawPitch', 'RHipRoll', 'RHipPitch', 'RKneePitch', 'AngleX', 'AngleY'], where 'AngleX' and 'AngleY' are body angle (e.g. ```Perception.imu```) and others are joint angles.

## 2. Data preprocessing

In [1]:
%pylab inline
import pickle
from os import listdir, path
import numpy as np
from sklearn import svm, metrics

ROBOT_POSE_DATA_DIR = 'robot_pose_data'

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


In [2]:
classes = listdir(ROBOT_POSE_DATA_DIR)
print (classes)

['HeadBack', 'Crouch', 'StandInit', 'Belly', 'Sit', 'Knee', 'Left', 'Back', 'Frog', 'Stand', 'Right']


In [3]:
def load_pose_data(i):
    '''load pose data from file'''
    data = []
    target = []
    # YOUR CODE HERE
    filename = path.join(ROBOT_POSE_DATA_DIR, classes[i])
    data = pickle.load(open(filename, 'rb'))
    target = [i] * len(data)
    return data, target

In [4]:
# load all the data
all_data = []
all_target = []
# YOUR CODE HERE
for i in range(len(classes)):
    data, target = load_pose_data(i)
    all_data.extend(data)
    all_target.extend(target)


print ('total number of data', len(all_data))

total number of data 224


In [58]:
# shuffule data
permutation = np.random.permutation(len(all_data))
n_training_data = int(len(all_data) * 0.7)
training_data = permutation[:n_training_data]#
training_data

array([ 45,  33,  75,  59,  69, 137,  12, 130,  15, 211,  58, 183, 190,
        76, 153, 169,  57,  50,   1,  72, 157,  36,  53,  56, 115, 143,
       165,  30, 127, 111,  24, 199, 113, 182, 222,  94,  73,  74,  20,
        96, 124,  32, 141,   3, 210,   8,  43,  93,  86, 148, 110,  90,
       107,   9, 128, 154, 191,  79,  21,  10, 187, 101, 208, 186, 102,
       103, 116, 216,  49,  87, 219,   6, 201, 132, 159, 168, 204,  41,
       122,  26, 184,  44, 194, 104,  13,  91, 100,  82,  70,  19, 178,
       193, 220,  28, 156,  77, 188,  39,  85,   5, 131, 166,  80, 214,
        66, 123, 173, 212,   7, 138,  25,  31,  18,  78, 215, 185,  83,
       218,   2, 125,  61, 175, 117, 158, 135, 160, 134, 195, 109, 180,
        51, 205, 162, 192,  48, 146, 126, 161, 142, 174,  40,  46, 177,
        35, 108,  95, 140,  97,  54,  98, 181,  11,   0, 217, 119,  89])

## 3. Learn on training data

In scikit-learn, an estimator for classification is a Python object that implements the methods fit(X, y) and predict(T). An example of an estimator is the class sklearn.svm.SVC that implements support vector classification.

In [59]:
clf = svm.SVC(gamma=0.001, C=100.)

### learning

In [60]:
# YOUR CODE HERE
t_data = []
t_target = []
for i in training_data:
    t_data.append(all_data[i])
    t_target.append(all_target[i])


clf.fit(t_data, t_target)

SVC(C=100.0, gamma=0.001)

### predicting

In [89]:
for i in range (len(training_data)):
    print(clf.predict(np.array(all_data[i]).reshape(1, -1)), all_target[i])


[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6


In [90]:
def evaluate(expected, predicted):
    print("Classification report:\n%s\n" % metrics.classification_report(expected, predicted))

    print("Confusion matrix:\n%s" % metrics.confusion_matrix(expected, predicted))

In [94]:
expected = []
predicted = []
# YOUR CODE HERE
test_data = []

for i in range(len(all_data)):
    if(i in training_data):
        continue
    expected.append(all_target[i])
    test_data.append(all_data[i])


predicted = clf.predict(test_data)


evaluate(expected, predicted)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        15
           3       1.00      1.00      1.00         4
           4       1.00      1.00      1.00         8
           5       1.00      1.00      1.00         3
           6       1.00      1.00      1.00         8
           7       1.00      1.00      1.00         7
           8       1.00      1.00      1.00         4
           9       1.00      1.00      1.00         5
          10       1.00      1.00      1.00         2

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67


Confusion matrix:
[[ 1  0  0  0  0  0  0  0  0  0  0]
 [ 0 10  0  0  0  0  0  0  0  0  0]
 [ 0  0 15  0  0  0  0  0  0  0  0]
 [ 0  0  0  4  0  0  0  0  0  0  0]
 

## 4. Evaluate on the test data

In [83]:
expected = []
predicted = []
# YOUR CODE HERE

evaluate(expected, predicted)

Classification report:
             precision    recall  f1-score   support

          0       1.00      1.00      1.00         5
          1       1.00      1.00      1.00         3
          2       1.00      1.00      1.00         5
          3       1.00      1.00      1.00         5
          4       0.91      1.00      0.95        10
          5       1.00      1.00      1.00         4
          6       1.00      1.00      1.00         2
          7       1.00      0.75      0.86         4
          8       1.00      1.00      1.00         8
          9       1.00      1.00      1.00         3
         10       1.00      1.00      1.00        11

avg / total       0.98      0.98      0.98        60


Confusion matrix:
[[ 5  0  0  0  0  0  0  0  0  0  0]
 [ 0  3  0  0  0  0  0  0  0  0  0]
 [ 0  0  5  0  0  0  0  0  0  0  0]
 [ 0  0  0  5  0  0  0  0  0  0  0]
 [ 0  0  0  0 10  0  0  0  0  0  0]
 [ 0  0  0  0  0  4  0  0  0  0  0]
 [ 0  0  0  0  0  0  2  0  0  0  0]
 [ 0  0  0  0 

## 5. Deploy to the real system

We can simple use `pickle` module to serialize the trained classifier.

In [97]:
import pickle
ROBOT_POSE_CLF = 'robot_pose.pkl'
pickle.dump(clf, open(ROBOT_POSE_CLF, 'wb'))

Then, in the application we can load the trained classifier again.

In [111]:
clf2 = pickle.load(open(ROBOT_POSE_CLF, "rb"))
for i in range(len(all_data)):
    print(clf2.predict(np.array(all_data[i]).reshape(1,-1)), all_target[i])

[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[0] 0
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[1] 1
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[2] 2
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[3] 3
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[4] 4
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[5] 5
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 6
[6] 